// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRKR-S2XK62eL__CTe06mTCPpfM1IbdME',
    appId: '1:403183920888:web:119f64b9036244888ffd0d',
    messagingSenderId: '403183920888',
    projectId: 'projeto-integrador-9c237',
    authDomain: 'projeto-integrador-9c237.firebaseapp.com',
    storageBucket: 'projeto-integrador-9c237.firebasestorage.app',
    measurementId: 'G-N4HMDYG4TG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHY1dxAfvcKwkUe1FlToVlmaXAkRrUsGc',
    appId: '1:403183920888:android:1909ce9c8e1f9b2f8ffd0d',
    messagingSenderId: '403183920888',
    projectId: 'projeto-integrador-9c237',
    storageBucket: 'projeto-integrador-9c237.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClwGGMsXFp4QMwpzsSIc5rOb8xUK92w-U',
    appId: '1:403183920888:ios:8c4756080a7aa8788ffd0d',
    messagingSenderId: '403183920888',
    projectId: 'projeto-integrador-9c237',
    storageBucket: 'projeto-integrador-9c237.firebasestorage.app',
    iosBundleId: 'com.example.rpgProjetoIntegrador',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClwGGMsXFp4QMwpzsSIc5rOb8xUK92w-U',
    appId: '1:403183920888:ios:8c4756080a7aa8788ffd0d',
    messagingSenderId: '403183920888',
    projectId: 'projeto-integrador-9c237',
    storageBucket: 'projeto-integrador-9c237.firebasestorage.app',
    iosBundleId: 'com.example.rpgProjetoIntegrador',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRKR-S2XK62eL__CTe06mTCPpfM1IbdME',
    appId: '1:403183920888:web:c17f393db78a67a08ffd0d',
    messagingSenderId: '403183920888',
    projectId: 'projeto-integrador-9c237',
    authDomain: 'projeto-integrador-9c237.firebaseapp.com',
    storageBucket: 'projeto-integrador-9c237.firebasestorage.app',
    measurementId: 'G-B8P4DXE8DJ',
  );
}